// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

import 'package:meta/meta.dart';

@immutable
class JiraSprint {
  final int id;
  final String self;
  final String name;
  final DateTime? startDate;
  final DateTime? endDate;
  final String state;
  final String goal;
  const JiraSprint({
    this.id = 0,
    this.self = '',
    this.name = '',
    this.startDate,
    this.endDate,
    this.state = '',
    this.goal = '',
  });

  JiraSprint copyWith({
    int? id,
    String? self,
    String? name,
    DateTime? startDate,
    DateTime? endDate,
    String? state,
    String? goal,
  }) {
    return JiraSprint(
      id: id ?? this.id,
      self: self ?? this.self,
      name: name ?? this.name,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      state: state ?? this.state,
      goal: goal ?? this.goal,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'self': self,
      'name': name,
      'start_date': startDate?.toIso8601String(),
      'end_date': endDate?.toIso8601String(),
      'state': state,
      'goal': goal,
    };
  }

  factory JiraSprint.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return JiraSprint(
      id: cast<num?>('id')?.toInt() ?? 0,
      self: cast<String?>('self') ?? '',
      name: cast<String?>('name') ?? '',
      startDate: map['start_date'] != null
          ? DateTime.parse(cast<String>('start_date'))
          : null,
      endDate: map['end_date'] != null
          ? DateTime.parse(cast<String>('end_date'))
          : null,
      state: cast<String?>('state') ?? '',
      goal: cast<String?>('goal') ?? '',
    );
  }

  String toJson() => json.encode(toMap());

  factory JiraSprint.fromJson(String source) =>
      JiraSprint.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''JiraSprint(
      id: $id,
      self: $self,
      name: $name,
      startDate: $startDate,
      endDate: $endDate,
      state: $state,
      goal: $goal,
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is JiraSprint &&
        other.id == id &&
        other.self == self &&
        other.name == name &&
        other.startDate == startDate &&
        other.endDate == endDate &&
        other.state == state &&
        other.goal == goal;
  }

  @override
  int get hashCode {
    return id.hashCode ^
        self.hashCode ^
        name.hashCode ^
        startDate.hashCode ^
        endDate.hashCode ^
        state.hashCode ^
        goal.hashCode;
  }
}
