# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/ispect"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/ispect_layout"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/ispectify"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/ispectify_bloc"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/ispectify_db"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/ispectify_dio"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/ispectify_http"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/ispectify_ws"
    schedule:
      interval: "weekly"
