// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:async';
import 'dart:convert';

import 'package:collection/collection.dart';
import 'package:flutter/widgets.dart';
import 'package:ispectify/ispectify.dart';

/// Invoked when the user shares logs from the inspector panel.
///
/// Implementations typically hand [request] to `share_plus` or a platform
/// share sheet.
typedef ISpectShareCallback = Future<void> Function(ISpectShareRequest request);

/// Invoked when the user taps an exported log file path in the viewer.
///
/// Implementations typically open the file with `open_file` or similar.
typedef ISpectOpenFileCallback = Future<void> Function(String path);

/// Invoked when the log viewer needs to load log content from an external
/// source (file picker, clipboard, URL, etc.).
///
/// Return the raw log content as a string, or `null` if the user cancelled.
typedef ISpectLoadLogContentCallback = Future<String?> Function(
  BuildContext context,
);

/// Called when ISpect settings change (logger options, enabled log types, etc.).
///
/// Use this callback to persist settings to local storage and restore them
/// on next app launch.
///
/// Example:
/// ```dart
/// onSettingsChanged: (settings) async {
///   await storage.write('ispect_settings', settings.toJson());
/// },
/// ```
typedef ISpectSettingsChangedCallback = void Function(
  ISpectSettingsState settings,
);

/// Mirrors `ISpectLoggerOptions.maxHistoryItems` default.
const int kDefaultMaxHistoryItems = 10000;

/// Mirrors `ISpectLoggerOptions.logTruncateLength` default
/// (`kDefaultStringTruncateLimit`).
const int kDefaultLogTruncateLength = 10000;

/// Snapshot of every runtime-configurable ISpect setting exposed in the
/// Settings sheet. Serialized via [toJson] and restored on app restart
/// through `ISpectOptions.initialSettings`.
@immutable
final class ISpectSettingsState {
  const ISpectSettingsState({
    required this.enabled,
    required this.useConsoleLogs,
    required this.useHistory,
    this.forwardErrorToConsole = false,
    this.maxHistoryItems = kDefaultMaxHistoryItems,
    this.logTruncateLength = kDefaultLogTruncateLength,
    this.disabledLogTypes = const {},
    this.expandedLogs = false,
    this.isLogOrderReversed = true,
    this.groupHttpLogs = true,
    this.useRelativeTime = false,
    this.compactNetworkUrls = true,
    this.isLogPageEnabled = true,
    this.isPerformanceEnabled = true,
    this.isInspectorEnabled = true,
    this.isColorPickerEnabled = true,
  })  : assert(maxHistoryItems >= 0, 'maxHistoryItems must be non-negative'),
        assert(
          logTruncateLength >= 0,
          'logTruncateLength must be non-negative',
        );

  final bool enabled;
  final bool useConsoleLogs;
  final bool useHistory;

  /// Forwards `error` and `stackTrace` to `dart:developer.log`, surfacing
  /// them separately in DevTools/IDE consoles at the cost of duplication
  /// in plain-text terminals.
  final bool forwardErrorToConsole;

  final int maxHistoryItems;
  final int logTruncateLength;

  /// Disabled [ISpectLogType.key] values. Empty set means "all enabled".
  final Set<String> disabledLogTypes;

  final bool expandedLogs;
  final bool isLogOrderReversed;
  final bool groupHttpLogs;
  final bool useRelativeTime;

  /// Renders network transaction rows with only the path and query, dropping
  /// the shared scheme and host so the endpoint is visible without expanding.
  final bool compactNetworkUrls;

  final bool isLogPageEnabled;
  final bool isPerformanceEnabled;
  final bool isInspectorEnabled;
  final bool isColorPickerEnabled;

  bool get isAllLogTypesEnabled => disabledLogTypes.isEmpty;

  bool isLogTypeEnabled(String logTypeKey) =>
      !disabledLogTypes.contains(logTypeKey);

  ISpectSettingsState copyWith({
    bool? enabled,
    bool? useConsoleLogs,
    bool? useHistory,
    bool? forwardErrorToConsole,
    int? maxHistoryItems,
    int? logTruncateLength,
    Set<String>? disabledLogTypes,
    bool? expandedLogs,
    bool? isLogOrderReversed,
    bool? groupHttpLogs,
    bool? useRelativeTime,
    bool? compactNetworkUrls,
    bool? isLogPageEnabled,
    bool? isPerformanceEnabled,
    bool? isInspectorEnabled,
    bool? isColorPickerEnabled,
  }) {
    return ISpectSettingsState(
      enabled: enabled ?? this.enabled,
      useConsoleLogs: useConsoleLogs ?? this.useConsoleLogs,
      useHistory: useHistory ?? this.useHistory,
      forwardErrorToConsole:
          forwardErrorToConsole ?? this.forwardErrorToConsole,
      maxHistoryItems: maxHistoryItems ?? this.maxHistoryItems,
      logTruncateLength: logTruncateLength ?? this.logTruncateLength,
      disabledLogTypes: disabledLogTypes ?? this.disabledLogTypes,
      expandedLogs: expandedLogs ?? this.expandedLogs,
      isLogOrderReversed: isLogOrderReversed ?? this.isLogOrderReversed,
      groupHttpLogs: groupHttpLogs ?? this.groupHttpLogs,
      useRelativeTime: useRelativeTime ?? this.useRelativeTime,
      compactNetworkUrls: compactNetworkUrls ?? this.compactNetworkUrls,
      isLogPageEnabled: isLogPageEnabled ?? this.isLogPageEnabled,
      isPerformanceEnabled: isPerformanceEnabled ?? this.isPerformanceEnabled,
      isInspectorEnabled: isInspectorEnabled ?? this.isInspectorEnabled,
      isColorPickerEnabled: isColorPickerEnabled ?? this.isColorPickerEnabled,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'enabled': enabled,
      'use_console_logs': useConsoleLogs,
      'use_history': useHistory,
      'forward_error_to_console': forwardErrorToConsole,
      'max_history_items': maxHistoryItems,
      'log_truncate_length': logTruncateLength,
      'disabled_log_types': disabledLogTypes.toList(growable: false),
      'expanded_logs': expandedLogs,
      'is_log_order_reversed': isLogOrderReversed,
      'group_http_logs': groupHttpLogs,
      'use_relative_time': useRelativeTime,
      'compact_network_urls': compactNetworkUrls,
      'is_log_page_enabled': isLogPageEnabled,
      'is_performance_enabled': isPerformanceEnabled,
      'is_inspector_enabled': isInspectorEnabled,
      'is_color_picker_enabled': isColorPickerEnabled,
    };
  }

  factory ISpectSettingsState.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return ISpectSettingsState(
      enabled: cast<bool?>('enabled') ?? false,
      useConsoleLogs: cast<bool?>('use_console_logs') ?? false,
      useHistory: cast<bool?>('use_history') ?? false,
      forwardErrorToConsole: cast<bool?>('forward_error_to_console') ?? false,
      maxHistoryItems: cast<int?>('max_history_items') ?? 0,
      logTruncateLength: cast<int?>('log_truncate_length') ?? 0,
      disabledLogTypes: Set<String>.from(
          cast<Iterable<dynamic>?>('disabled_log_types') ?? const <String>{}),
      expandedLogs: cast<bool?>('expanded_logs') ?? false,
      isLogOrderReversed: cast<bool?>('is_log_order_reversed') ?? false,
      groupHttpLogs: cast<bool?>('group_http_logs') ?? false,
      useRelativeTime: cast<bool?>('use_relative_time') ?? false,
      compactNetworkUrls: cast<bool?>('compact_network_urls') ?? true,
      isLogPageEnabled: cast<bool?>('is_log_page_enabled') ?? false,
      isPerformanceEnabled: cast<bool?>('is_performance_enabled') ?? false,
      isInspectorEnabled: cast<bool?>('is_inspector_enabled') ?? false,
      isColorPickerEnabled: cast<bool?>('is_color_picker_enabled') ?? false,
    );
  }

  String toJson() => json.encode(toMap());

  factory ISpectSettingsState.fromJson(String source) =>
      ISpectSettingsState.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() {
    return '''ISpectSettingsState(
      enabled: $enabled,
      useConsoleLogs: $useConsoleLogs,
      useHistory: $useHistory,
      forwardErrorToConsole: $forwardErrorToConsole,
      maxHistoryItems: $maxHistoryItems,
      logTruncateLength: $logTruncateLength,
      disabledLogTypes: $disabledLogTypes,
      expandedLogs: $expandedLogs,
      isLogOrderReversed: $isLogOrderReversed,
      groupHttpLogs: $groupHttpLogs,
      useRelativeTime: $useRelativeTime,
      compactNetworkUrls: $compactNetworkUrls,
      isLogPageEnabled: $isLogPageEnabled,
      isPerformanceEnabled: $isPerformanceEnabled,
      isInspectorEnabled: $isInspectorEnabled,
      isColorPickerEnabled: $isColorPickerEnabled
      )''';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final setEquals = const DeepCollectionEquality().equals;

    return other is ISpectSettingsState &&
        other.enabled == enabled &&
        other.useConsoleLogs == useConsoleLogs &&
        other.useHistory == useHistory &&
        other.forwardErrorToConsole == forwardErrorToConsole &&
        other.maxHistoryItems == maxHistoryItems &&
        other.logTruncateLength == logTruncateLength &&
        setEquals(other.disabledLogTypes, disabledLogTypes) &&
        other.expandedLogs == expandedLogs &&
        other.isLogOrderReversed == isLogOrderReversed &&
        other.groupHttpLogs == groupHttpLogs &&
        other.useRelativeTime == useRelativeTime &&
        other.compactNetworkUrls == compactNetworkUrls &&
        other.isLogPageEnabled == isLogPageEnabled &&
        other.isPerformanceEnabled == isPerformanceEnabled &&
        other.isInspectorEnabled == isInspectorEnabled &&
        other.isColorPickerEnabled == isColorPickerEnabled;
  }

  @override
  int get hashCode {
    return Object.hash(
        enabled,
        useConsoleLogs,
        useHistory,
        forwardErrorToConsole,
        maxHistoryItems,
        logTruncateLength,
        disabledLogTypes,
        expandedLogs,
        isLogOrderReversed,
        groupHttpLogs,
        useRelativeTime,
        compactNetworkUrls,
        isLogPageEnabled,
        isPerformanceEnabled,
        isInspectorEnabled,
        isColorPickerEnabled);
  }
}

/// Describes content to pass into a custom share handler.
@immutable
final class ISpectShareRequest {
  /// Optional subject line (used by platforms that support it, e.g. email).
  final String? subject;

  /// Plain-text payload to share.
  final String? text;

  /// Absolute file paths to share as attachments.
  final List<String> filePaths;
  const ISpectShareRequest({
    this.subject,
    this.text,
    this.filePaths = const [],
  });

  /// Whether [filePaths] contains at least one entry.
  bool get hasFiles => filePaths.isNotEmpty;

  static const Object _sentinel = Object();
  ISpectShareRequest copyWith({
    Object? subject = _sentinel,
    Object? text = _sentinel,
    List<String>? filePaths,
  }) {
    return ISpectShareRequest(
      subject: subject == _sentinel ? this.subject : (subject as String?),
      text: text == _sentinel ? this.text : (text as String?),
      filePaths: filePaths ?? this.filePaths,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'subject': subject,
      'text': text,
      'file_paths': filePaths,
    };
  }

  factory ISpectShareRequest.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return ISpectShareRequest(
      subject: cast<String?>('subject'),
      text: cast<String?>('text'),
      filePaths:
          List<String>.from(cast<List<dynamic>?>('file_paths') ?? const []),
    );
  }

  String toJson() => json.encode(toMap());

  factory ISpectShareRequest.fromJson(String source) =>
      ISpectShareRequest.fromMap(json.decode(source) as Map<String, dynamic>);

  @override
  String toString() => '''ISpectShareRequest(
      subject: $subject,
      text: $text,
      filePaths: $filePaths
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final listEquals = const DeepCollectionEquality().equals;

    return other is ISpectShareRequest &&
        other.subject == subject &&
        other.text == text &&
        listEquals(other.filePaths, filePaths);
  }

  @override
  int get hashCode => Object.hash(subject, text, filePaths);
}
