// ignore_for_file: use_if_null_to_convert_nulls_to_bools

// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:collection/collection.dart';
import 'package:draggable_panel/draggable_panel.dart';
import 'package:flutter/material.dart';
import 'package:ispect/src/common/models/action_item.dart';
import 'package:ispect/src/common/plugins/inspector_plugin.dart';
import 'package:ispect/src/common/widgets/builder/data_builder.dart';
import 'package:ispect/src/core/res/ispect_callbacks.dart';
import 'package:ispect/src/core/res/ispect_panel.dart';

/// A configuration class for `ISpect`, defining various options including locale settings,
/// feature toggles, action items, and panel configurations.
///
/// This class allows customization of `ISpect` through parameters such as:
/// - Language settings (`locale`).
/// - Feature toggles (`isLogPageEnabled`, `isPerformanceEnabled`, etc.).
/// - Action items (`actionItems`).
/// - Custom panel items (`panelItems`).
/// - Additional panel buttons (`panelButtons`).
/// - Custom log card builder (`logBuilder`).
///
/// ### Example Usage:
/// ```dart
/// final options = ISpectOptions(
///   locale: const Locale('en'),
///   isLogPageEnabled: true,
///   isPerformanceEnabled: false,
///   actionItems: [
///     ISpectActionItem(
///       title: 'Clear Logs',
///       icon: Icons.clear_all,
///       onTap: (context) => clearLogs(),
///     ),
///   ],
///   panelItems: [
///     ISpectPanelItem(
///       icon: Icons.bug_report,
///       enableBadge: true,
///       onTap: (context) => showBugReport(context),
///     ),
///   ],
///   panelButtons: [
///     ISpectPanelButtonItem(
///       icon: Icons.settings,
///       label: 'Settings',
///       onTap: (context) => openSettings(context),
///     ),
///   ],
/// );
/// ```
@immutable
final class ISpectOptions {
  const ISpectOptions({
    this.locale = const Locale('en'),
    this.observer,
    this.isLogPageEnabled = true,
    this.isPerformanceEnabled = true,
    this.enableJankLogging = false,
    this.severeJankFactor = 2.0,
    this.isInspectorEnabled = true,
    this.isColorPickerEnabled = true,
    this.actionItems = const [],
    this.panelItems = const [],
    this.panelButtons = const [],
    this.panelBuilder,
    this.plugins = const [],
    this.logBuilder,
    this.onShare,
    this.onOpenFile,
    this.onLoadLogContent,
    this.onSettingsChanged,
    this.initialSettings,
    this.metadataProvider,
  });

  /// The locale setting for `ISpect`, defining the language and region preferences.
  ///
  /// Defaults to `Locale('en')`.
  final Locale locale;

  /// A navigator observer to track navigation events within the app.
  final NavigatorObserver? observer;

  /// Controls visibility of the log viewer page.
  ///
  /// When `true`, the log page will be available in the ISpect interface.
  /// Defaults to `true`.
  final bool isLogPageEnabled;

  /// Controls visibility of performance monitoring tools.
  ///
  /// When `true`, performance monitoring features will be available.
  /// Defaults to `true`.
  final bool isPerformanceEnabled;

  /// Routes frames where `totalSpan > target × severeJankFactor` through
  /// [`ISpect.logger`](ISpect.logger) under [`performanceCategory`]. Off by
  /// default to avoid log spam; enable when you want jank entries in the log
  /// viewer.
  final bool enableJankLogging;

  /// Multiplier applied to the frame-time budget when deciding whether a
  /// frame counts as severe jank. `2.0` matches "visible hitch" on 60Hz.
  /// Ignored unless [enableJankLogging] is `true`.
  final double severeJankFactor;

  /// Controls visibility of the widget inspector.
  ///
  /// When `true`, the widget inspector will be available for debugging UI.
  /// Defaults to `true`.
  final bool isInspectorEnabled;

  /// Controls visibility of the color picker tool.
  ///
  /// When `true`, the color picker utility will be available.
  /// Defaults to `true`.
  final bool isColorPickerEnabled;

  /// A list of custom action items that can be triggered in `ISpect`.
  ///
  /// Each action item contains:
  /// - `title`: The display name of the action
  /// - `icon`: The icon representing the action
  /// - `onTap`: A callback function triggered when the action is executed
  ///
  /// This typically includes debugging, logging, or inspection actions.
  final List<ISpectActionItem> actionItems;

  /// A list of panel items displayed in the `ISpect` interface.
  ///
  /// Each panel item is an `ISpectPanelItem` with the following properties:
  /// - `icon`: The icon representing the panel item
  /// - `enableBadge`: A flag to determine if a notification badge should be shown
  /// - `onTap`: A callback function triggered when the item is tapped
  final List<DraggablePanelItem> panelItems;

  /// A list of panel buttons for additional controls in the `ISpect` interface.
  ///
  /// Each panel button is an `ISpectPanelButtonItem` with the following properties:
  /// - `icon`: The button's icon
  /// - `label`: The text label displayed for the button
  /// - `onTap`: A callback function triggered when the button is tapped
  final List<DraggablePanelButtonItem> panelButtons;

  /// Builds the entire draggable diagnostics panel, replacing ISpect's default
  /// `DraggablePanel`.
  ///
  /// ISpect still assembles the items (built-in tools + [panelItems] + plugins),
  /// [panelButtons], the controller, and the default theme, and hands them to
  /// the builder via [ISpectPanelData]. Return a `DraggablePanel` configured
  /// however you like — every `draggable_panel` parameter (content/shell
  /// builders, motion, behavior flags, tooltips, sizing) is available here,
  /// including ones added in future `draggable_panel` releases, without ISpect
  /// forwarding each one.
  ///
  /// ```dart
  /// ISpectOptions(
  ///   panelBuilder: (context, data) => DraggablePanel(
  ///     controller: data.controller,
  ///     items: data.items,
  ///     buttons: data.buttons,
  ///     theme: data.theme.copyWith(panelWidth: 240),
  ///     panelHeight: 320,
  ///     child: data.child,
  ///   ),
  /// )
  /// ```
  final ISpectPanelBuilder? panelBuilder;

  /// A list of plugins that extend the inspector panel with custom screens.
  ///
  /// Each plugin provides an icon, title, and screen that will be added
  /// to the draggable panel. Plugins also support lifecycle hooks
  /// ([InspectorPlugin.onInit] and [InspectorPlugin.onDispose]).
  final List<InspectorPlugin> plugins;

  /// Custom builder for log card widget. If null, uses default card.
  ///
  /// When provided, completely replaces the default log card rendering
  /// in both mobile and desktop layouts.
  ///
  /// Example:
  /// ```dart
  /// ISpectOptions(
  ///   logBuilder: (context, log) => MyCustomLogCard(log: log),
  /// )
  /// ```
  final ISpectLogDataBuilder? logBuilder;

  /// Custom handler for share actions triggered inside ISpect.
  ///
  /// When provided, built-in share buttons delegate to this callback instead of
  /// relying on external packages. If omitted, share-related UI is hidden.
  final ISpectShareCallback? onShare;

  /// Custom handler for file opening actions triggered inside ISpect.
  ///
  /// When provided, locations that previously relied on external packages will
  /// call this callback with a file system path. UI that requires it is hidden
  /// when no callback is supplied.
  final ISpectOpenFileCallback? onOpenFile;

  /// Custom loader invoked when the log viewer needs raw content from a file.
  ///
  /// When omitted, ISpect relies solely on the paste flow. Return `null` to
  /// cancel the loading operation without showing an error.
  final ISpectLoadLogContentCallback? onLoadLogContent;

  /// Called when ISpect settings change (logger options, enabled log types, etc.).
  ///
  /// Use this callback to persist settings to local storage and restore them
  /// on next app launch.
  ///
  /// Example:
  /// ```dart
  /// onSettingsChanged: (settings) async {
  ///   final prefs = await SharedPreferences.getInstance();
  ///   await prefs.setString('ispect_settings', jsonEncode(settings.toJson()));
  /// },
  /// ```
  final ISpectSettingsChangedCallback? onSettingsChanged;

  /// Initial settings state to restore from local storage.
  ///
  /// Use this to restore previously saved settings when initializing ISpect.
  ///
  /// Example:
  /// ```dart
  /// final prefs = await SharedPreferences.getInstance();
  /// final settingsJson = prefs.getString('ispect_settings');
  /// final initialSettings = settingsJson != null
  ///     ? ISpectSettingsState.fromJson(jsonDecode(settingsJson))
  ///     : null;
  ///
  /// ISpect.init(
  ///   options: ISpectOptions(
  ///     initialSettings: initialSettings,
  ///     onSettingsChanged: (settings) async {
  ///       await prefs.setString('ispect_settings', jsonEncode(settings.toJson()));
  ///     },
  ///   ),
  /// );
  /// ```
  final ISpectSettingsState? initialSettings;

  /// Supplies environment metadata (app version, device, OS, …) embedded into
  /// the header of exported/shared log files.
  ///
  /// When omitted, exports carry no environment metadata. ISpect never
  /// collects these values itself — the host app provides them, keeping
  /// `package_info_plus`/`device_info_plus` out of ISpect's dependencies.
  final ISpectMetadataProvider? metadataProvider;

  /// Creates a new `ISpectOptions` instance with updated values while retaining
  /// existing ones where not specified.
  ///
  /// All parameters are optional and when provided will override the corresponding
  /// values in the current instance.
  ///
  /// ### Example Usage:
  /// ```dart
  /// final updatedOptions = options.copyWith(
  ///   locale: const Locale('es'),
  ///   isLogPageEnabled: false,
  /// );
  /// ```
  ISpectOptions copyWith({
    Locale? locale,
    NavigatorObserver? observer,
    bool? isLogPageEnabled,
    bool? isPerformanceEnabled,
    bool? enableJankLogging,
    double? severeJankFactor,
    bool? isInspectorEnabled,
    bool? isColorPickerEnabled,
    List<ISpectActionItem>? actionItems,
    List<DraggablePanelItem>? panelItems,
    List<DraggablePanelButtonItem>? panelButtons,
    ISpectPanelBuilder? panelBuilder,
    List<InspectorPlugin>? plugins,
    ISpectLogDataBuilder? logBuilder,
    ISpectShareCallback? onShare,
    ISpectOpenFileCallback? onOpenFile,
    ISpectLoadLogContentCallback? onLoadLogContent,
    ISpectSettingsChangedCallback? onSettingsChanged,
    ISpectSettingsState? initialSettings,
    ISpectMetadataProvider? metadataProvider,
  }) {
    return ISpectOptions(
      locale: locale ?? this.locale,
      observer: observer ?? this.observer,
      isLogPageEnabled: isLogPageEnabled ?? this.isLogPageEnabled,
      isPerformanceEnabled: isPerformanceEnabled ?? this.isPerformanceEnabled,
      enableJankLogging: enableJankLogging ?? this.enableJankLogging,
      severeJankFactor: severeJankFactor ?? this.severeJankFactor,
      isInspectorEnabled: isInspectorEnabled ?? this.isInspectorEnabled,
      isColorPickerEnabled: isColorPickerEnabled ?? this.isColorPickerEnabled,
      actionItems: actionItems ?? this.actionItems,
      panelItems: panelItems ?? this.panelItems,
      panelButtons: panelButtons ?? this.panelButtons,
      panelBuilder: panelBuilder ?? this.panelBuilder,
      plugins: plugins ?? this.plugins,
      logBuilder: logBuilder ?? this.logBuilder,
      onShare: onShare ?? this.onShare,
      onOpenFile: onOpenFile ?? this.onOpenFile,
      onLoadLogContent: onLoadLogContent ?? this.onLoadLogContent,
      onSettingsChanged: onSettingsChanged ?? this.onSettingsChanged,
      initialSettings: initialSettings ?? this.initialSettings,
      metadataProvider: metadataProvider ?? this.metadataProvider,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final listEquals = const DeepCollectionEquality().equals;

    return other is ISpectOptions &&
        other.locale == locale &&
        other.observer == observer &&
        other.isLogPageEnabled == isLogPageEnabled &&
        other.isPerformanceEnabled == isPerformanceEnabled &&
        other.enableJankLogging == enableJankLogging &&
        other.severeJankFactor == severeJankFactor &&
        other.isInspectorEnabled == isInspectorEnabled &&
        other.isColorPickerEnabled == isColorPickerEnabled &&
        listEquals(other.actionItems, actionItems) &&
        listEquals(other.panelItems, panelItems) &&
        listEquals(other.panelButtons, panelButtons) &&
        other.panelBuilder == panelBuilder &&
        listEquals(other.plugins, plugins) &&
        other.logBuilder == logBuilder &&
        other.onShare == onShare &&
        other.onOpenFile == onOpenFile &&
        other.onLoadLogContent == onLoadLogContent &&
        other.onSettingsChanged == onSettingsChanged &&
        other.initialSettings == initialSettings &&
        other.metadataProvider == metadataProvider;
  }

  static const _deepEquality = DeepCollectionEquality();

  @override
  int get hashCode {
    return Object.hash(
      locale,
      observer,
      isLogPageEnabled,
      isPerformanceEnabled,
      enableJankLogging,
      severeJankFactor,
      isInspectorEnabled,
      isColorPickerEnabled,
      _deepEquality.hash(actionItems),
      _deepEquality.hash(panelItems),
      _deepEquality.hash(panelButtons),
      panelBuilder,
      _deepEquality.hash(plugins),
      logBuilder,
      onShare,
      onOpenFile,
      onLoadLogContent,
      onSettingsChanged,
      initialSettings,
      metadataProvider,
    );
  }

  @override
  String toString() {
    return '''ISpectOptions(
      locale: $locale,
      observer: $observer,
      isLogPageEnabled: $isLogPageEnabled,
      isPerformanceEnabled: $isPerformanceEnabled,
      enableJankLogging: $enableJankLogging,
      severeJankFactor: $severeJankFactor,
      isInspectorEnabled: $isInspectorEnabled,
      isColorPickerEnabled: $isColorPickerEnabled,
      actionItems: $actionItems,
      panelItems: $panelItems,
      panelButtons: $panelButtons,
      panelBuilder: $panelBuilder,
      plugins: $plugins,
      logBuilder: $logBuilder,
      onShare: $onShare,
      onOpenFile: $onOpenFile,
      onLoadLogContent: $onLoadLogContent,
      onSettingsChanged: $onSettingsChanged,
      initialSettings: $initialSettings,
      metadataProvider: $metadataProvider,
      )''';
  }
}
