// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:async';

import 'package:collection/collection.dart';
import 'package:flutter/widgets.dart';
import 'package:ispectify/ispectify.dart';

/// Invoked when the user shares logs from the inspector panel.
///
/// Implementations typically hand [request] to `share_plus` or a platform
/// share sheet.
typedef ISpectShareCallback = Future<void> Function(ISpectShareRequest request);

/// Invoked when the user taps an exported log file path in the viewer.
///
/// Implementations typically open the file with `open_file` or similar.
typedef ISpectOpenFileCallback = Future<void> Function(String path);

/// Invoked when the log viewer needs to load log content from an external
/// source (file picker, clipboard, URL, etc.).
///
/// Return the raw log content as a string, or `null` if the user cancelled.
typedef ISpectLoadLogContentCallback = Future<String?> Function(
  BuildContext context,
);

/// Called when ISpect settings change (logger options, enabled log types, etc.).
///
/// Use this callback to persist settings to local storage and restore them
/// on next app launch.
///
/// Example:
/// ```dart
/// onSettingsChanged: (settings) async {
///   await storage.write('ispect_settings', settings.toJson());
/// },
/// ```
typedef ISpectSettingsChangedCallback = void Function(
  ISpectSettingsState settings,
);

/// Represents the current state of ISpect settings.
///
/// This class encapsulates all configurable settings including:
/// - Logger enabled state
/// - Console logs enabled state
/// - History enabled state
/// - Disabled log types for filtering
///
/// Can be serialized to JSON for persistence and restored on app restart.
@immutable
final class ISpectSettingsState {
  /// Creates a snapshot of the current ISpect settings.
  const ISpectSettingsState({
    required this.enabled,
    required this.useConsoleLogs,
    required this.useHistory,
    this.disabledLogTypes = const {},
  });

  /// Whether logging is enabled globally.
  final bool enabled;

  /// Whether console logging is enabled.
  final bool useConsoleLogs;

  /// Whether log history storage is enabled.
  final bool useHistory;

  /// Set of disabled log type keys. If empty, all log types are enabled.
  ///
  /// Use [ISpectLogType.key] values to populate this set.
  final Set<String> disabledLogTypes;

  /// Returns true if all log types are enabled (no disabled types).
  bool get isAllLogTypesEnabled => disabledLogTypes.isEmpty;

  /// Returns true if a specific log type is enabled (not in disabled set).
  bool isLogTypeEnabled(String logTypeKey) {
    return !disabledLogTypes.contains(logTypeKey);
  }

  /// Converts settings to JSON for persistence.
  Map<String, dynamic> toJson() => {
        'enabled': enabled,
        'useConsoleLogs': useConsoleLogs,
        'useHistory': useHistory,
        'disabledLogTypes': disabledLogTypes.toList(),
      };

  /// Creates settings from JSON, falling back to permissive defaults when
  /// fields are missing.
  factory ISpectSettingsState.fromJson(Map<String, dynamic> json) {
    return ISpectSettingsState(
      enabled: json['enabled'] as bool? ?? true,
      useConsoleLogs: json['useConsoleLogs'] as bool? ?? true,
      useHistory: json['useHistory'] as bool? ?? true,
      disabledLogTypes: (json['disabledLogTypes'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toSet() ??
          const {},
    );
  }

  /// Returns a copy with the provided fields replaced.
  ISpectSettingsState copyWith({
    bool? enabled,
    bool? useConsoleLogs,
    bool? useHistory,
    Set<String>? disabledLogTypes,
  }) {
    return ISpectSettingsState(
      enabled: enabled ?? this.enabled,
      useConsoleLogs: useConsoleLogs ?? this.useConsoleLogs,
      useHistory: useHistory ?? this.useHistory,
      disabledLogTypes: disabledLogTypes ?? this.disabledLogTypes,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final setEquals = const DeepCollectionEquality().equals;

    return other is ISpectSettingsState &&
        other.enabled == enabled &&
        other.useConsoleLogs == useConsoleLogs &&
        other.useHistory == useHistory &&
        setEquals(other.disabledLogTypes, disabledLogTypes);
  }

  @override
  int get hashCode => Object.hash(
        enabled,
        useConsoleLogs,
        useHistory,
        const DeepCollectionEquality().hash(disabledLogTypes),
      );

  @override
  String toString() => '''ISpectSettingsState(
      enabled: $enabled,
      useConsoleLogs: $useConsoleLogs,
      useHistory: $useHistory,
      disabledLogTypes: $disabledLogTypes,
      )''';
}

/// Describes content to pass into a custom share handler.
@immutable
final class ISpectShareRequest {
  /// Creates a share request. At least one of [text] or [filePaths] should
  /// be provided for the share to be meaningful.
  const ISpectShareRequest({
    this.subject,
    this.text,
    this.filePaths = const [],
  });

  /// Optional subject line (used by platforms that support it, e.g. email).
  final String? subject;

  /// Plain-text payload to share.
  final String? text;

  /// Absolute file paths to share as attachments.
  final List<String> filePaths;

  /// Whether [filePaths] contains at least one entry.
  bool get hasFiles => filePaths.isNotEmpty;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final listEquals = const DeepCollectionEquality().equals;

    return other is ISpectShareRequest &&
        other.subject == subject &&
        other.text == text &&
        listEquals(other.filePaths, filePaths);
  }

  @override
  int get hashCode => Object.hash(
        subject,
        text,
        const DeepCollectionEquality().hash(filePaths),
      );

  @override
  String toString() => '''ISpectShareRequest(
      subject: $subject,
      text: $text,
      filePaths: $filePaths,
      )''';

  /// Returns a copy with the provided fields replaced.
  ISpectShareRequest copyWith({
    String? subject,
    String? text,
    List<String>? filePaths,
  }) {
    return ISpectShareRequest(
      subject: subject ?? this.subject,
      text: text ?? this.text,
      filePaths: filePaths ?? this.filePaths,
    );
  }
}
