// ignore_for_file: prefer_const_constructor_declarations, cascade_invocations

// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint

import 'package:flutter/material.dart';
import 'package:ispect/ispect.dart';
import 'package:ispect/src/common/observers/route_extension.dart';
import 'package:ispect/src/common/observers/transition.dart';

/// Extension on `StringBuffer` to conditionally write a line.
extension StringBufferExtension on StringBuffer {
  /// Writes `value` to the buffer if [condition] is true.
  // ignore: avoid_positional_boolean_parameters
  void writelnIf(bool condition, String value) {
    if (condition) writeln(value);
  }
}

/// A custom `NavigatorObserver` for logging navigation events.
///
/// This observer logs page transitions, modals, gestures, and other navigation events.
/// It provides callbacks for external listeners and allows filtering of specific event types.
class ISpectNavigatorObserver extends NavigatorObserver {
  /// Creates an instance of `ISpectNavigatorObserver`.
  ///
  /// - `isLogGestures`: Whether to log user gestures.
  /// - `isLogPages`: Whether to log page navigations.
  /// - `isLogModals`: Whether to log modal transitions.
  /// - `isLogOtherTypes`: Whether to log other navigation types.
  ISpectNavigatorObserver({
    this.isLogGestures = false,
    this.isLogPages = true,
    this.isLogModals = false,
    this.isLogOtherTypes = true,
    this.isLogInternalRoutes = false,
    this.onPush,
    this.onReplace,
    this.onPop,
    this.onRemove,
    this.onStartUserGesture,
    this.onStopUserGesture,
    this.maxTransitions = 200,
    this.enableArgumentRedaction = true,
  });

  /// The most recently installed `ISpectNavigatorObserver`.
  ///
  /// Populated by [observers] when ISpect is enabled. Lets `ISpectBuilder`
  /// auto-wire the route observer for the navigation drill-down screen
  /// without requiring callers to pass the same instance into both
  /// `MaterialApp.navigatorObservers` and `ISpectOptions.observer`.
  ///
  /// Always `null` in builds where `kISpectEnabled` is `false`.
  static ISpectNavigatorObserver? get current => _current;
  static ISpectNavigatorObserver? _current;

  /// Resets the [current] slot. Intended for `ISpect.dispose()` and tests.
  static void resetCurrent() => _current = null;

  /// Returns a list of navigator observers for use in MaterialApp.
  ///
  /// When `kISpectEnabled` is `true`, includes the ISpect observer and
  /// publishes it via [current] so `ISpectBuilder.wrap` can pick it up
  /// without explicit `ISpectOptions.observer` wiring. Repeated calls reuse
  /// the auto-created singleton.
  ///
  /// When `kISpectEnabled` is `false`, returns only [additional] observers
  /// and never touches [current].
  ///
  /// Simple usage:
  /// ```dart
  /// MaterialApp(
  ///   navigatorObservers: ISpectNavigatorObserver.observers(),
  ///   builder: (_, child) => ISpectBuilder.wrap(child: child!),
  /// )
  /// ```
  ///
  /// With full customization:
  /// ```dart
  /// MaterialApp(
  ///   navigatorObservers: ISpectNavigatorObserver.observers(
  ///     observer: ISpectNavigatorObserver(
  ///       onPush: (route, prev) => print('pushed'),
  ///       onPop: (route, prev) => print('popped'),
  ///       isLogGestures: true,
  ///     ),
  ///     additional: [AnalyticsObserver()],
  ///   ),
  /// )
  /// ```
  static List<NavigatorObserver> observers({
    ISpectNavigatorObserver? observer,
    List<NavigatorObserver> additional = const [],
  }) {
    if (!kISpectEnabled) return additional;

    final effective = observer ?? _current ?? ISpectNavigatorObserver();
    _current = effective;

    return [effective, ...additional];
  }

  final int maxTransitions;
  final List<RouteTransition> _transitions = [];

  /// Maps Route → stable correlationId so push/pop/replace/remove share one ID.
  final Expando<String> _routeCorrelationIds = Expando<String>('route_corr_id');

  List<RouteTransition> get transitions => List.unmodifiable(_transitions);

  void addTransition(RouteTransition transition) {
    _transitions.add(transition);
    if (_transitions.length > maxTransitions) {
      _transitions.removeAt(0);
    }
  }

  final bool isLogGestures;
  final bool isLogPages;
  final bool isLogModals;
  final bool isLogOtherTypes;

  final bool isLogInternalRoutes;

  final void Function(Route<dynamic> route, Route<dynamic>? previousRoute)?
      onPush;
  final void Function({Route<dynamic>? newRoute, Route<dynamic>? oldRoute})?
      onReplace;
  final void Function(Route<dynamic> route, Route<dynamic>? previousRoute)?
      onPop;
  final void Function(Route<dynamic> route, Route<dynamic>? previousRoute)?
      onRemove;
  final void Function(Route<dynamic> route, Route<dynamic>? previousRoute)?
      onStartUserGesture;
  final VoidCallback? onStopUserGesture;

  /// When true, route arguments are redacted in log messages by showing
  /// only their type and key names (no values). Defaults to true for security.
  /// Set to false to include full argument details in logs.
  final bool enableArgumentRedaction;

  @override
  void didPush(Route<dynamic> route, Route<dynamic>? previousRoute) {
    onPush?.call(route, previousRoute);
    _logRouteEvent(TransitionType.push, route, previousRoute);
  }

  @override
  void didReplace({Route<dynamic>? newRoute, Route<dynamic>? oldRoute}) {
    onReplace?.call(newRoute: newRoute, oldRoute: oldRoute);
    _logRouteEvent(TransitionType.replace, newRoute, oldRoute);
  }

  @override
  void didPop(Route<dynamic> route, Route<dynamic>? previousRoute) {
    onPop?.call(route, previousRoute);
    _logRouteEvent(TransitionType.pop, previousRoute, route);
  }

  @override
  void didRemove(Route<dynamic> route, Route<dynamic>? previousRoute) {
    onRemove?.call(route, previousRoute);
    _logRouteEvent(TransitionType.remove, route, previousRoute);
  }

  @override
  void didStartUserGesture(
    Route<dynamic> route,
    Route<dynamic>? previousRoute,
  ) {
    if (isLogGestures) {
      _logRouteEvent(TransitionType.startUserGesture, route, previousRoute);
    }
    onStartUserGesture?.call(route, previousRoute);
  }

  @override
  void didStopUserGesture() {
    if (isLogGestures) {
      _logRouteEvent(TransitionType.stopUserGesture, null, null);
    }
    onStopUserGesture?.call();
  }

  /// Logs navigation events based on event type and route validation.
  void _logRouteEvent(
    TransitionType type,
    Route<dynamic>? route,
    Route<dynamic>? previousRoute,
  ) {
    if (!kISpectEnabled) return;
    if (!_shouldLog(route, previousRoute)) return;

    final correlationId = _resolveCorrelationId(type, route, previousRoute);

    final timestamp = DateTime.now();
    final transition = _createRouteTransition(
      type: type,
      route: route,
      previousRoute: previousRoute,
      timestamp: timestamp,
    );

    addTransition(transition);

    final logMessage = _buildLogMessage(type, route, previousRoute);
    ISpect.logger.route(logMessage, transitionId: correlationId);
  }

  String? _resolveCorrelationId(
    TransitionType type,
    Route<dynamic>? route,
    Route<dynamic>? previousRoute,
  ) {
    if (type == TransitionType.push && route != null) {
      final id = generateTraceId();
      _routeCorrelationIds[route] = id;
      return id;
    }
    // Pop/remove/replace: check both routes (args are swapped in didPop)
    if (route != null) {
      final id = _routeCorrelationIds[route];
      if (id != null) return id;
    }
    if (previousRoute != null) {
      return _routeCorrelationIds[previousRoute];
    }
    return null;
  }

  String _generateTransitionId(DateTime timestamp, Route<dynamic>? route) {
    final micro = timestamp.microsecondsSinceEpoch;
    final routeId = route?.hashCode ?? 0;
    final instanceId = identityHashCode(this);

    final hash = Object.hash(micro, routeId, instanceId);

    return hash.toUnsigned(64).toRadixString(36);
  }

  /// Extracts lightweight [RouteMetadata] from a live [Route] object.
  static RouteMetadata? _extractMetadata(Route<dynamic>? route) {
    if (route == null) return null;
    return RouteMetadata(
      name: route.routeName,
      routeType: route.routeType,
    );
  }

  /// Creates a RouteTransition instance with proper ID generation.
  RouteTransition _createRouteTransition({
    required TransitionType type,
    required Route<dynamic>? route,
    required Route<dynamic>? previousRoute,
    required DateTime timestamp,
  }) {
    final id = _generateTransitionId(timestamp, route);

    return RouteTransition(
      id: id,
      from: _extractMetadata(previousRoute),
      to: _extractMetadata(route),
      type: type,
      timestamp: timestamp,
      arguments: route?.settings.arguments,
    );
  }

  /// Builds a structured log message for route transitions.
  String _buildLogMessage(
    TransitionType type,
    Route<dynamic>? route,
    Route<dynamic>? previousRoute,
  ) {
    final buffer = StringBuffer();
    final routeName = route.routeName;
    final routeType = route.routeType;
    final previousRouteName = previousRoute.routeName;
    final previousRouteType = previousRoute.routeType;

    buffer.writeln(
        '${type.title} | $previousRouteName ($previousRouteType) → $routeName ($routeType)');

    // Arguments info — redacted by default (only type and key names)
    switch (route?.settings.arguments) {
      case null:
        break;
      case final Map<String, dynamic> args:
        if (enableArgumentRedaction) {
          buffer.writeln('Arguments: {${args.keys.join(', ')}}');
        } else {
          buffer.writeln('Arguments: $args');
        }
      case final Object args:
        if (enableArgumentRedaction) {
          buffer.writeln('Arguments: (${args.runtimeType})');
        } else {
          buffer.writeln('Arguments: $args');
        }
    }

    return buffer.toString().trim();
  }

  /// Determines whether a route transition should be logged based on route types and configuration.
  ///
  /// This method evaluates the combination of route types in the transition against
  /// logging configuration flags to determine whether logging should occur.
  ///
  /// The logic follows these rules:
  /// 1. If both routes are PageRoutes, log only if `isLogPages` is true
  /// 2. If both routes are ModalRoutes (excluding PageRoutes), log only if `isLogModals` is true
  /// 3. If routes are of mixed types (e.g., one PageRoute and one ModalRoute), do not log
  /// 4. For any other route type combinations, log only if `isLogOtherTypes` is true
  ///
  /// - `route`: The new/current route being navigated to
  /// - `previousRoute`: The previous route being navigated from
  ///
  /// Returns true if the route transition should be logged based on current settings.
  bool _shouldLog(Route<dynamic>? route, Route<dynamic>? previousRoute) {
    if (!isLogInternalRoutes && _isInternalRoute(route)) return false;

    return switch ((route, previousRoute)) {
      // Both pages
      (PageRoute(), PageRoute()) => isLogPages,
      // Both modals (PageRoute is ModalRoute; Page/Page is handled above)
      (ModalRoute(), ModalRoute()) => isLogModals,
      // Mixed modal/non-modal
      (ModalRoute(), _) || (_, ModalRoute()) => false,
      // Other types
      _ => isLogOtherTypes,
    };
  }

  /// Prefix used by all internal ISpect route names.
  static const _internalRoutePrefix = 'ISpect';

  /// Returns true if the route belongs to the ISpect inspector UI itself.
  static bool _isInternalRoute(Route<dynamic>? route) {
    final name = route?.settings.name;
    return name != null && name.startsWith(_internalRoutePrefix);
  }
}
