// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint

import 'package:collection/collection.dart';
import 'package:flutter/material.dart';
import 'package:ispect/ispect.dart';

enum TransitionType {
  push,
  pop,
  replace,
  remove,
  startUserGesture,
  stopUserGesture;

  String get title => switch (this) {
        TransitionType.push => 'Push',
        TransitionType.pop => 'Pop',
        TransitionType.replace => 'Replace',
        TransitionType.remove => 'Remove',
        TransitionType.startUserGesture => 'Start User Gesture',
        TransitionType.stopUserGesture => 'Stop User Gesture',
      };
}

/// Lightweight metadata extracted from a [Route] to avoid retaining
/// the entire Route object (and its associated widget/render tree).
@immutable
class RouteMetadata {
  const RouteMetadata({
    required this.name,
    required this.routeType,
  });

  /// The resolved display name (from settings or fallback).
  final String name;

  /// A human-readable label for the route type (e.g. 'Page', 'Modal').
  final String routeType;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteMetadata &&
          name == other.name &&
          routeType == other.routeType;

  @override
  int get hashCode => Object.hash(name, routeType);

  @override
  String toString() => 'RouteMetadata(name: $name, routeType: $routeType)';
}

@immutable
class RouteTransition {
  const RouteTransition({
    required this.id,
    required this.from,
    required this.to,
    required this.type,
    required this.timestamp,
    required this.arguments,
  });

  final String id;
  final RouteMetadata? from;
  final RouteMetadata? to;
  // enum
  final TransitionType type;
  final DateTime timestamp;
  final Object? arguments;

  static const _equality = DeepCollectionEquality();

  String get transitionText {
    final fromName = from?.name ?? 'Unknown';
    final toName = to?.name ?? 'Unknown';
    return '$fromName → $toName';
  }

  String? get prettyArguments {
    final args = arguments;
    return switch (args) {
      null => null,
      final Map<String, dynamic> map => JsonTruncator.pretty(map),
      _ => args.toString(),
    };
  }

  @override
  String toString() => 'RouteTransition('
      'id: $id, '
      'from: $from, '
      'to: $to, '
      'type: $type, '
      'timestamp: $timestamp, '
      'arguments: $arguments'
      ')';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    if (other is! RouteTransition) {
      return false;
    }
    return id == other.id &&
        from == other.from &&
        to == other.to &&
        type == other.type &&
        timestamp == other.timestamp &&
        _equality.equals(arguments, other.arguments);
  }

  @override
  int get hashCode => Object.hash(
        id,
        from,
        to,
        type,
        timestamp,
        _equality.hash(arguments),
      );

  RouteTransition copyWith({
    String? id,
    RouteMetadata? from,
    RouteMetadata? to,
    TransitionType? type,
    DateTime? timestamp,
    Object? arguments,
  }) =>
      RouteTransition(
        id: id ?? this.id,
        from: from ?? this.from,
        to: to ?? this.to,
        type: type ?? this.type,
        timestamp: timestamp ?? this.timestamp,
        arguments: arguments ?? this.arguments,
      );
}
