name: ispect_jira_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependency_overrides:
  ispect:
    path: ../../ispect
  ispectify:
    path: ../../ispectify
  ispect_jira:
    path: ../

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_localizations:
    sdk: flutter
  ispect: ^4.4.0-dev04
  ispect_jira: ^4.4.0-dev04

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 120
