analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - use_key_in_widget_constructors
    - prefer_final_locals
    - always_declare_return_types
    - prefer_typing_uninitialized_variables
    - avoid_dynamic_calls
