output-class: ISpectGeneratedLocalization
main-locale: en
arb-dir: lib/src/core/localization/translations
output-dir: lib/src/core/localization/generated
template-arb-file: intl_en.arb
output-localization-file: ispect_localizations.dart
synthetic-package: false