class PresetService {
  static Map<String, Map<String, dynamic>> get presets => {
        'Light': {
          'requestCount': 1,
          'itemCount': 20,
          'nestingDepth': 2,
          'payloadSize': 16,
          'enableHttp': true,
          'enableWs': false,
          'enableLogging': true,
          'enableExceptions': false,
          'enableFileUploads': false,
          'enableAnalytics': false,
          'enableBlocEvents': false,
          'enableRoutes': true,
          'enableRiverpod': false,
          'httpMethod': 'GET',
          'useAuthHeader': false,
          'httpSendSuccess': true,
          'httpSendErrors': false,
          'wsMessageSize': 8,
          'loopDelayMs': 0,
          'randomize': false,
        },
        'Stress': {
          'requestCount': 10,
          'itemCount': 1000,
          'nestingDepth': 10,
          'payloadSize': 256,
          'enableHttp': true,
          'enableWs': true,
          'enableLogging': true,
          'enableExceptions': true,
          'enableFileUploads': true,
          'enableAnalytics': true,
          'enableBlocEvents': true,
          'enableRoutes': true,
          'enableRiverpod': true,
          'httpMethod': 'POST',
          'useAuthHeader': true,
          'httpSendSuccess': true,
          'httpSendErrors': true,
          'wsMessageSize': 64,
          'loopDelayMs': 10,
          'randomize': true,
        },
        'Network': {
          'requestCount': 5,
          'itemCount': 50,
          'nestingDepth': 3,
          'payloadSize': 64,
          'enableHttp': true,
          'enableWs': true,
          'enableLogging': false,
          'enableExceptions': false,
          'enableFileUploads': true,
          'enableAnalytics': false,
          'enableBlocEvents': false,
          'enableRoutes': false,
          'enableRiverpod': false,
          'httpMethod': 'GET',
          'useAuthHeader': true,
          'httpSendSuccess': true,
          'httpSendErrors': true,
          'wsMessageSize': 32,
          'loopDelayMs': 0,
          'randomize': true,
        },
        'Full': {
          'requestCount': 5,
          'itemCount': 200,
          'nestingDepth': 4,
          'payloadSize': 128,
          'enableHttp': true,
          'enableWs': true,
          'enableLogging': true,
          'enableExceptions': true,
          'enableFileUploads': true,
          'enableAnalytics': true,
          'enableBlocEvents': true,
          'enableRoutes': true,
          'enableRiverpod': true,
          'httpMethod': 'POST',
          'useAuthHeader': true,
          'httpSendSuccess': true,
          'httpSendErrors': true,
          'wsMessageSize': 32,
          'loopDelayMs': 5,
          'randomize': true,
        },
      };

  static void applyPreset(
      String preset, Function(Map<String, dynamic>) onApply) {
    final config = presets[preset];
    if (config != null) {
      onApply(config);
    }
  }
}
