name: ispect_jira
description: "An additional package for ISpect to create Jira tickets"
version: 4.1.3-dev12
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  atlassian_apis: ^0.15.0
  ispect: ^4.1.3-dev11
  flutter_bloc: ^9.1.0
  meta: ^1.15.0
  file_picker: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
