name: ispect_jira
description: "An additional package for ISpect to create Jira tickets"
version: 4.3.6
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ^3.6.0

dependency_overrides:
  ispect:
    path: ../ispect

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Explicit version constraint required (avoid 'any').
  intl: ^0.20.0

  atlassian_apis: ^0.15.0
  ispect: ^4.3.6
  flutter_bloc: ^9.1.0
  # Align meta with core package to reduce duplication.
  meta: ^1.16.0
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
