name: ispect_jira
description: "A package combining Inspector, ISpectiy, and more from pub.dev for efficient project implementation."
version: 0.0.2
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  atlassian_apis: ^0.15.0
  ispect:
    path: ../ispect
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  gap: ^3.0.1
  file_picker: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
