import 'dart:io';

import 'package:path/path.dart' as p;

import 'exceptions.dart';
import 'version_config.dart';

const String _outputPath = 'llms.txt';
const String _rootPubspecPath = 'packages/ispect/pubspec.yaml';
const String _projectTitle = 'ISpect';

const String _red = '\x1B[0;31m';
const String _green = '\x1B[0;32m';
const String _blue = '\x1B[0;34m';
const String _reset = '\x1B[0m';

final RegExp _leadingHashes = RegExp('^#[\t\n\v\f\r ]*');
final RegExp _trailingNewlines = RegExp(r'\n+$');

/// What one run does with the generated index.
enum LlmsMode {
  /// Write `llms.txt`.
  write,

  /// Compare the render against `llms.txt` without writing.
  check,

  /// Print the render without writing.
  dryRun,
}

/// Generates the repo-root `llms.txt` navigation index from repository
/// metadata, so the index tracks pubspecs, examples, and docs with no
/// hand-edits.
final class LlmsBuilder {
  const LlmsBuilder({
    required this.repoRoot,
    required this.out,
    required this.err,
  });

  final String repoRoot;
  final StringSink out;
  final StringSink err;

  /// The full text of `llms.txt`, terminated by exactly one newline.
  ///
  /// Throws [VersionConfigException] when `version.config` is missing or does
  /// not declare a semantic version.
  String render() {
    final version = VersionConfig.forRepo(repoRoot).read().toString();

    final rootPubspec = File(p.join(repoRoot, _rootPubspecPath));
    final repository = _pubspecField(rootPubspec, 'repository');
    final summary = _pubspecField(rootPubspec, 'description');

    final lines = <String>[
      '<!-- Generated by bash/build_llms.sh — do not edit by hand. Rerun the '
          'script after changing packages, interceptors, or docs. -->',
      '',
      '# $_projectTitle',
      '',
      '> $summary',
      '',
      'ISpect is a Flutter/Dart monorepo of focused diagnostics packages. '
          'This index points AI',
      'agents and tooling at the canonical, always-current sources so they '
          'can read what they',
      "need on demand instead of working from memorized API. Treat each "
          "package's exported",
      '`lib/<package>.dart` and `README.md` as the authoritative API surface.',
      '',
      '- Repository: $repository',
      '- Version: $version',
      '',
      '## Integration prompt',
      '',
    ];

    if (File(p.join(repoRoot, 'docs', 'prompt.md')).existsSync()) {
      lines.add('- [docs/prompt.md](docs/prompt.md): paste-ready prompt for '
          'an AI agent to integrate ISpect into a Flutter app.');
    }
    lines
      ..add('')
      ..add('## Packages')
      ..add('');

    final packageDirs = _packageDirectories();
    for (final directory in packageDirs) {
      final pubspec = File(p.join(directory, 'pubspec.yaml'));
      if (!pubspec.existsSync()) {
        continue;
      }
      final name = _pubspecField(pubspec, 'name');
      if (name.isEmpty) {
        continue;
      }
      final description = _pubspecField(pubspec, 'description');
      lines.add('- [$name](${_relative(directory)}/README.md): $description');
    }

    lines
      ..add('')
      ..add('## Setup examples')
      ..add('');

    for (final directory in packageDirs) {
      final name =
          _pubspecField(File(p.join(directory, 'pubspec.yaml')), 'name');
      if (name.isEmpty) {
        continue;
      }
      final entry = _exampleEntry(directory);
      if (entry == null) {
        continue;
      }
      lines.add('- [$entry]($entry): example wiring for `$name`.');
    }
    lines.add('');

    _addInterceptorSection(
      lines,
      directory: p.join(
        repoRoot,
        'packages/ispectify_db/example/lib/interceptors',
      ),
      heading: '## Database interceptors (reference implementations to copy)',
    );
    _addInterceptorSection(
      lines,
      directory: p.join(
        repoRoot,
        'packages/ispectify_ws/example/lib/interceptors',
      ),
      heading: '## WebSocket adapters (reference implementations to copy)',
    );

    lines
      ..add('## Docs')
      ..add('');

    for (final doc
        in _sortedFiles(Directory(p.join(repoRoot, 'docs')), '.md')) {
      if (p.basename(doc) == 'prompt.md') {
        continue;
      }
      lines.add('- [${_docTitle(File(doc))}](${_relative(doc)})');
    }

    return '${lines.join('\n').replaceAll(_trailingNewlines, '')}\n';
  }

  /// Applies [mode] to the rendered index and reports whether it is current.
  ///
  /// Returns false only in [LlmsMode.check] when `llms.txt` disagrees with the
  /// render.
  ///
  /// Throws [VersionConfigException] when `version.config` is missing.
  bool run(LlmsMode mode) {
    final contents = render();
    final output = File(p.join(repoRoot, _outputPath));

    switch (mode) {
      case LlmsMode.dryRun:
        out.write(contents);
        return true;
      case LlmsMode.check:
        if (output.existsSync() && output.readAsStringSync() == contents) {
          out.writeln('$_green✓ $_outputPath is up to date$_reset');
          return true;
        }
        err.writeln(
          '$_red✗ $_outputPath is out of date — run ./bash/build_llms.sh'
          '$_reset',
        );
        return false;
      case LlmsMode.write:
        output.writeAsStringSync(contents);
        out.writeln('$_green✓ Generated$_reset $_blue$_outputPath$_reset');
        return true;
    }
  }

  void _addInterceptorSection(
    List<String> lines, {
    required String directory,
    required String heading,
  }) {
    if (!Directory(directory).existsSync()) {
      return;
    }
    lines
      ..add(heading)
      ..add('');
    for (final file in _sortedFiles(Directory(directory), '.dart')) {
      lines.add('- [${prettyInterceptorName(file)}](${_relative(file)})');
    }
    lines.add('');
  }

  List<String> _packageDirectories() {
    final packages = Directory(p.join(repoRoot, 'packages'));
    if (!packages.existsSync()) {
      return const [];
    }
    return packages
        .listSync()
        .whereType<Directory>()
        .map((directory) => directory.path)
        .toList()
      ..sort();
  }

  String? _exampleEntry(String packageDir) {
    for (final candidate in [
      p.join(packageDir, 'example', 'lib', 'main.dart'),
      p.join(packageDir, 'example', 'main.dart'),
    ]) {
      if (File(candidate).existsSync()) {
        return _relative(candidate);
      }
    }

    final candidates = <String>[
      for (final directory in [
        Directory(p.join(packageDir, 'example', 'lib')),
        Directory(p.join(packageDir, 'example')),
      ])
        ..._sortedFiles(directory, '.dart'),
    ]..sort();

    for (final candidate in candidates) {
      if (!p.basename(candidate).endsWith('.g.dart')) {
        return _relative(candidate);
      }
    }
    return null;
  }

  List<String> _sortedFiles(Directory directory, String extension) {
    if (!directory.existsSync()) {
      return const [];
    }
    return directory
        .listSync()
        .whereType<File>()
        .map((file) => file.path)
        .where((path) => path.endsWith(extension))
        .toList()
      ..sort();
  }

  String _docTitle(File doc) {
    for (final line in _splitLines(doc.readAsStringSync())) {
      if (line.startsWith('# ')) {
        return line.replaceFirst(_leadingHashes, '');
      }
    }
    return p.basenameWithoutExtension(doc.path);
  }

  String _pubspecField(File pubspec, String key) {
    if (!pubspec.existsSync()) {
      return '';
    }
    for (final line in _splitLines(pubspec.readAsStringSync())) {
      if (!line.startsWith('$key:')) {
        continue;
      }
      var value = line.substring(key.length + 1).trimLeft();
      if (value.startsWith('"') || value.startsWith("'")) {
        value = value.substring(1);
      }
      if (value.endsWith('"') || value.endsWith("'")) {
        value = value.substring(0, value.length - 1);
      }
      return value;
    }
    return '';
  }

  String _relative(String path) => p.relative(path, from: repoRoot);
}

/// A reference-implementation filename rendered as a title.
///
/// `flutter_secure_storage_interceptor.dart` becomes
/// `Flutter Secure Storage`.
String prettyInterceptorName(String path) {
  var base = p.basename(path);
  if (base.endsWith('.dart')) {
    base = base.substring(0, base.length - '.dart'.length);
  }
  if (base.endsWith('_interceptor')) {
    base = base.substring(0, base.length - '_interceptor'.length);
  }
  return base
      .split('_')
      .map((word) =>
          word.isEmpty ? word : word[0].toUpperCase() + word.substring(1))
      .join(' ');
}

/// Parses [arguments], generates the index, and returns the process exit code.
///
/// Accepts `--check` and `--dry-run`. Returns 1 when `--check` finds the index
/// out of date and 2 for a usage or configuration failure.
int runLlmsBuild({
  required String repoRoot,
  required List<String> arguments,
  StringSink? out,
  StringSink? err,
}) {
  final output = out ?? stdout;
  final errors = err ?? stderr;

  final LlmsMode mode;
  switch (arguments.isEmpty ? '' : arguments.first) {
    case '--check':
      mode = LlmsMode.check;
    case '--dry-run':
      mode = LlmsMode.dryRun;
    case '':
      mode = LlmsMode.write;
    default:
      errors
        ..writeln('${_red}Unknown option: ${arguments.first}$_reset')
        ..writeln('Usage: build_llms [--check|--dry-run]');
      return 2;
  }

  final builder = LlmsBuilder(repoRoot: repoRoot, out: output, err: errors);
  try {
    return builder.run(mode) ? 0 : 1;
  } on ToolException catch (e) {
    errors.writeln('$_red${e.message}$_reset');
    return 2;
  }
}

List<String> _splitLines(String contents) {
  final lines = contents.split('\n');
  if (lines.isNotEmpty && lines.last.isEmpty) {
    lines.removeLast();
  }
  return lines;
}
