// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:convert';

import 'package:meta/meta.dart';

@immutable
final class LogDescription {
  final String key;

  /// Human-readable display name for the filter chip.
  /// When `null`, the chip formats [key] automatically
  /// (e.g. `'http-request'` → `'Http Request'`).
  final String? title;

  final String? description;
  final bool isDisabled;
  const LogDescription({
    required this.key,
    this.title,
    this.description,
    this.isDisabled = false,
  });

  LogDescription copyWith({
    String? key,
    String? title,
    String? description,
    bool? isDisabled,
  }) {
    return LogDescription(
      key: key ?? this.key,
      title: title ?? this.title,
      description: description ?? this.description,
      isDisabled: isDisabled ?? this.isDisabled,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'key': key,
      'title': title,
      'description': description,
      'is_disabled': isDisabled,
    };
  }

  factory LogDescription.fromMap(Map<String, dynamic> map) {
    T cast<T>(String k) => map[k] is T
        ? map[k] as T
        : throw ArgumentError.value(map[k], k, '$T ← ${map[k].runtimeType}');
    return LogDescription(
      key: cast<String?>('key') ?? '',
      title: cast<String?>('title'),
      description: cast<String?>('description'),
      isDisabled: cast<bool?>('is_disabled') ?? false,
    );
  }

  String toJson() => json.encode(toMap());

  factory LogDescription.fromJson(String source) =>
      LogDescription.fromMap(json.decode(source) as Map<String, dynamic>);

  /// Human-readable display title.
  ///
  /// Returns [title] if explicitly set; otherwise formats [key] by replacing
  /// hyphens with spaces and capitalising each word
  /// (e.g. `'http-request'` → `'Http Request'`).
  String get displayTitle =>
      title ??
      key
          .split('-')
          .map((w) => w.isEmpty ? w : '${w[0].toUpperCase()}${w.substring(1)}')
          .join(' ');

  @override
  String toString() => '''LogDescription(
      key: $key,
      title: $title,
      description: $description,
      isDisabled: $isDisabled,
      )''';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is LogDescription &&
        other.key == key &&
        other.title == title &&
        other.description == description &&
        other.isDisabled == isDisabled;
  }

  @override
  int get hashCode => Object.hash(key, title, description, isDisabled);
}
