name: ispect
description: In-app observability and QA diagnostics toolkit for Flutter, with logs, network tracing, layout inspection, exports, and redaction.
version: 5.0.4
homepage: https://github.com/yelmuratoff/ispect
repository: https://github.com/yelmuratoff/ispect
issue_tracker: https://github.com/yelmuratoff/ispect/issues

topics:
  - inspector
  - ispect
  - debug
  - toolkit
  - debug-toolkit

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

environment:
  sdk: ">=3.6.0 <4.0.0"

dependency_overrides:
  ispectify:
    path: ../ispectify
  ispect_layout:
    path: ../ispect_layout

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0
  flutter_localizations:
    sdk: flutter
  meta: ^1.16.0
  collection: ^1.19.1

  # Logging
  ispectify: ^5.0.4

  # Utils
  path_provider: ^2.1.5
  web: ^1.1.1

  # UI
  ispect_layout: ^5.0.4
  draggable_panel: ^2.0.2
  super_sliver_list: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
