@TestOn('vm')
library;

import 'dart:convert';
import 'dart:io';

import 'package:ispect_tool/src/core/exceptions.dart';
import 'package:ispect_tool/src/core/llms_builder.dart';
import 'package:ispect_tool/src/core/repo_paths.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  final repoRoot = findRepoRoot(Directory.current.path);
  if (repoRoot == null) {
    throw StateError('llms tests must run inside the repository');
  }

  group('rendering the repository', () {
    test('reproduces the committed llms.txt byte for byte', () {
      final committed = File(p.join(repoRoot, 'llms.txt'));
      expect(
        committed.existsSync(),
        isTrue,
        reason: 'llms.txt is the oracle; it must exist',
      );

      final rendered = LlmsBuilder(
        repoRoot: repoRoot,
        out: StringBuffer(),
        err: StringBuffer(),
      ).render();

      expect(
        utf8.encode(rendered),
        utf8.encode(committed.readAsStringSync()),
        reason: 'the generated index drifted from the committed llms.txt. '
            'A difference limited to the order of docs/VERSION.md and '
            'docs/VERSION_MANAGEMENT.md is the known locale-collation gap: '
            'the committed file was generated by bash `sort` under '
            'en_US.UTF-8, which orders punctuation before letters, while '
            'this port sorts by code unit so its output does not depend on '
            'the machine locale. Resolving it regenerates llms.txt.',
      );
    });

    test('reports the committed llms.txt as up to date', () {
      final out = StringBuffer();
      final exitCode = runLlmsBuild(
        repoRoot: repoRoot,
        arguments: const ['--check'],
        out: out,
        err: StringBuffer(),
      );

      expect(exitCode, 0, reason: out.toString());
      expect(out.toString(), contains('llms.txt is up to date'));
    });
  });

  group('on a fixture repository', () {
    late Directory workspace;
    late String repo;

    setUp(() {
      workspace = Directory.systemTemp.createTempSync('ispect-llms-');
      repo = p.join(workspace.path, 'repo');
      _writeFixture(repo);
    });

    tearDown(() {
      if (workspace.existsSync()) {
        workspace.deleteSync(recursive: true);
      }
    });

    String render() => LlmsBuilder(
          repoRoot: repo,
          out: StringBuffer(),
          err: StringBuffer(),
        ).render();

    test('lists every package with its description', () {
      expect(
        render(),
        stringContainsInOrder([
          '## Packages',
          '- [ispect](packages/ispect/README.md): Flutter diagnostics shell.',
          '- [ispectify](packages/ispectify/README.md): Logging core.',
        ]),
      );
    });

    test('sorts packages by directory name', () {
      expect(
        render().indexOf('- [ispect]'),
        lessThan(render().indexOf('- [ispectify]')),
      );
    });

    test('takes the repository summary and link from the ispect pubspec', () {
      expect(render(), contains('> Flutter diagnostics shell.'));
      expect(
        render(),
        contains('- Repository: https://github.com/yelmuratoff/ispect'),
      );
    });

    test('reads the version from the first line of version.config', () {
      expect(render(), contains('- Version: 1.2.3'));
    });

    test('prefers example/lib/main.dart as the setup entrypoint', () {
      expect(
        render(),
        contains('- [packages/ispect/example/lib/main.dart]'
            '(packages/ispect/example/lib/main.dart): example wiring for '
            '`ispect`.'),
      );
    });

    test('falls back to the first non-generated dart file in the example', () {
      _write(
        p.join(repo, 'packages', 'ispectify', 'example', 'lib', 'a.g.dart'),
        'generated\n',
      );
      _write(
        p.join(repo, 'packages', 'ispectify', 'example', 'lib', 'b_demo.dart'),
        'demo\n',
      );

      expect(
        render(),
        contains('- [packages/ispectify/example/lib/b_demo.dart]'),
      );
    });

    test('omits a package with no example entrypoint', () {
      expect(render(), isNot(contains('example wiring for `ispect_layout`')));
    });

    test('lists database interceptors as titles', () {
      expect(
        render(),
        stringContainsInOrder([
          '## Database interceptors (reference implementations to copy)',
          '- [Flutter Secure Storage]'
              '(packages/ispectify_db/example/lib/interceptors/'
              'flutter_secure_storage_interceptor.dart)',
        ]),
      );
    });

    test('omits the interceptor section when the directory is absent', () {
      expect(render(), isNot(contains('## WebSocket adapters')));
    });

    test('titles docs from their first heading', () {
      expect(render(), contains('- [Security Policy](docs/SECURITY.md)'));
    });

    test('falls back to the filename when a doc has no heading', () {
      expect(render(), contains('- [NOTES](docs/NOTES.md)'));
    });

    test('excludes prompt.md from the docs list', () {
      expect(render(), isNot(contains('- [Prompt](docs/prompt.md)')));
    });

    test('links prompt.md under the integration prompt section', () {
      expect(
        render(),
        stringContainsInOrder([
          '## Integration prompt',
          '- [docs/prompt.md](docs/prompt.md): paste-ready prompt',
        ]),
      );
    });

    test('omits the prompt link when the file is absent', () {
      File(p.join(repo, 'docs', 'prompt.md')).deleteSync();

      expect(render(), isNot(contains('[docs/prompt.md]')));
    });

    test('ends the index with exactly one newline', () {
      expect(render(), endsWith('.md)\n'));
      expect(render(), isNot(endsWith('\n\n')));
    });

    test('writing produces a file a later check accepts', () {
      final written = runLlmsBuild(
        repoRoot: repo,
        arguments: const [],
        out: StringBuffer(),
        err: StringBuffer(),
      );
      final checked = runLlmsBuild(
        repoRoot: repo,
        arguments: const ['--check'],
        out: StringBuffer(),
        err: StringBuffer(),
      );

      expect(written, 0);
      expect(checked, 0);
    });

    test('check reports a stale index and writes nothing', () {
      runLlmsBuild(
        repoRoot: repo,
        arguments: const [],
        out: StringBuffer(),
        err: StringBuffer(),
      );
      final index = File(p.join(repo, 'llms.txt'));
      index.writeAsStringSync('stale\n');

      final err = StringBuffer();
      final exitCode = runLlmsBuild(
        repoRoot: repo,
        arguments: const ['--check'],
        out: StringBuffer(),
        err: err,
      );

      expect(exitCode, 1);
      expect(err.toString(), contains('llms.txt is out of date'));
      expect(index.readAsStringSync(), 'stale\n');
    });

    test('check reports a missing index as out of date', () {
      final exitCode = runLlmsBuild(
        repoRoot: repo,
        arguments: const ['--check'],
        out: StringBuffer(),
        err: StringBuffer(),
      );

      expect(exitCode, 1);
    });

    test('dry run prints the index without writing it', () {
      final out = StringBuffer();
      final exitCode = runLlmsBuild(
        repoRoot: repo,
        arguments: const ['--dry-run'],
        out: out,
        err: StringBuffer(),
      );

      expect(exitCode, 0);
      expect(out.toString(), contains('## Packages'));
      expect(File(p.join(repo, 'llms.txt')).existsSync(), isFalse);
    });

    test('a missing version.config is rejected', () {
      File(p.join(repo, 'version.config')).deleteSync();

      expect(
        () => render(),
        throwsA(isA<VersionConfigException>()),
      );
    });

    test('a missing version.config exits 2', () {
      File(p.join(repo, 'version.config')).deleteSync();

      final exitCode = runLlmsBuild(
        repoRoot: repo,
        arguments: const [],
        out: StringBuffer(),
        err: StringBuffer(),
      );

      expect(exitCode, 2);
    });

    test('an unknown option exits 2', () {
      final err = StringBuffer();
      final exitCode = runLlmsBuild(
        repoRoot: repo,
        arguments: const ['--nope'],
        out: StringBuffer(),
        err: err,
      );

      expect(exitCode, 2);
      expect(err.toString(), contains('Unknown option: --nope'));
    });
  });

  group('interceptor titles', () {
    test('drops the interceptor suffix and title-cases the words', () {
      expect(
        prettyInterceptorName('a/b/flutter_secure_storage_interceptor.dart'),
        'Flutter Secure Storage',
      );
    });

    test('title-cases a filename that carries no interceptor suffix', () {
      expect(prettyInterceptorName('hive_box.dart'), 'Hive Box');
    });

    test('leaves an already capitalised word alone', () {
      expect(prettyInterceptorName('SQL_store.dart'), 'SQL Store');
    });
  });
}

void _writeFixture(String repo) {
  _write(p.join(repo, 'version.config'), 'VERSION=1.2.3\nCHANNEL=dev\n');

  _write(p.join(repo, 'packages', 'ispect', 'pubspec.yaml'), '''
name: ispect
description: Flutter diagnostics shell.
repository: https://github.com/yelmuratoff/ispect
version: 1.2.3
''');
  _write(
    p.join(repo, 'packages', 'ispect', 'example', 'lib', 'main.dart'),
    'void main() {}\n',
  );

  _write(p.join(repo, 'packages', 'ispectify', 'pubspec.yaml'), '''
name: ispectify
description: Logging core.
version: 1.2.3
''');

  _write(p.join(repo, 'packages', 'ispect_layout', 'pubspec.yaml'), '''
name: ispect_layout
description: Layout inspector.
version: 1.2.3
''');

  _write(
    p.join(
      repo,
      'packages',
      'ispectify_db',
      'example',
      'lib',
      'interceptors',
      'flutter_secure_storage_interceptor.dart',
    ),
    'class FlutterSecureStorageInterceptor {}\n',
  );

  _write(p.join(repo, 'docs', 'SECURITY.md'), '# Security Policy\n\nBody.\n');
  _write(p.join(repo, 'docs', 'NOTES.md'), 'No heading here.\n');
  _write(p.join(repo, 'docs', 'prompt.md'), '# Prompt\n\nBody.\n');
}

void _write(String path, String contents) {
  final file = File(path);
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(contents);
}
