name: ispect_ai
description: "An additional package for ISpect to interact with logs using Google Gemini AI"
version: 0.0.4-dev.2
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_bloc: ^9.0.0
  google_generative_ai: ^0.4.6
  path_provider: ^2.1.5
  ispect: ^3.0.0-dev.3
  meta: ^1.15.0
  flutter_markdown: ^0.7.4
  gap: ^3.0.1
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
