name: web_logs_viewer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependency_overrides:
  ispect:
    path: ../packages/ispect
  ispectify:
    path: ../packages/ispectify
  ispectify_http:
    path: ../packages/ispectify_http
  ispectify_bloc:
    path: ../packages/ispectify_bloc
  ispectify_dio:
    path: ../packages/ispectify_dio
  ispectify_ws:
    path: ../packages/ispectify_ws
  ispectify_db:
    path: ../packages/ispectify_db

dependencies:
  flutter:
    sdk: flutter
  ispect: ^4.4.7
  ispectify_dio: ^4.4.7
  ispectify_http: ^4.4.7
  ispectify_bloc: ^4.4.7
  ispectify_ws: ^4.4.7
  ispectify_db: ^4.4.7

  file_picker: ^10.3.3
  super_drag_and_drop: ^0.9.1
  collection: any
  dio: ^5.8.0+1
  dio_web_adapter: ^2.1.1
  ws: ^1.0.0
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  http_interceptor: ^2.0.0
  flutter_riverpod: ^2.5.1
  share_plus: ^12.0.0
  open_filex: ^4.7.0
  auto_route:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
