name: web_logs_viewer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependency_overrides:
  ispect:
    path: ../packages/ispect
  ispectify:
    path: ../packages/ispectify

dependencies:
  flutter:
    sdk: flutter
  ispect: ^4.4.6
  file_picker: ^10.3.3
  super_drag_and_drop: ^0.9.1
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
