// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:typed_data';

import 'package:collection/collection.dart';
import 'package:meta/meta.dart';

/// Container for the feedback of the user.
@immutable
class UserFeedback {
  const UserFeedback({
    required this.text,
    required this.screenshot,
    this.extra,
  });

  /// The user's written feedback
  final String text;

  /// A raw png encoded screenshot of the app. Probably annotated with helpful
  /// drawings by the user.
  final Uint8List screenshot;

  /// This can contain additional information. By default this is always empty.
  /// When using a custom `BetterFeedback.feedbackBuilder` this can be used
  /// to supply additional information.
  final Map<String, dynamic>? extra;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    final mapEquals = const DeepCollectionEquality().equals;

    return other is UserFeedback &&
        other.text == text &&
        other.screenshot == screenshot &&
        mapEquals(other.extra, extra);
  }

  @override
  int get hashCode => text.hashCode ^ screenshot.hashCode ^ extra.hashCode;
}
