name: ispect_device
description: "An additional package for ISpect to retrieve platform information"
version: 0.0.2-dev.3
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # Utils
  path_provider: ^2.1.5
  share_plus: ^10.1.3
  package_info_plus: ^8.1.2
  device_info_plus: ^11.2.0
  ispect: ^3.0.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
