name: ispect_device
description: "An additional package for ISpect to retrieve platform information"
version: 4.0.9-dev02
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # Utils
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  ispect: ^4.0.9-dev02

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
