name: ispect_device
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Utils
  path_provider: ^2.1.5
  share_plus: ^10.0.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  ispect:
    path: ../ispect

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
