#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TEMP_ROOT="$(cd "${TMPDIR:-/tmp}" && pwd -P)"
TEST_TMP="$(mktemp -d "$TEMP_ROOT/ispect-update-versions-test.XXXXXX")"
FAKE_BIN="$TEST_TMP/bin"
FAILURES=0

cleanup() {
  case $TEST_TMP in
    "$TEMP_ROOT"/ispect-update-versions-test.*)
      rm -rf -- "$TEST_TMP"
      ;;
    *)
      echo "refusing to remove unexpected test path: $TEST_TMP" >&2
      return 1
      ;;
  esac
}
trap cleanup EXIT

mkdir -p "$FAKE_BIN"

cat > "$FAKE_BIN/flutter" <<'FAKE_FLUTTER'
#!/usr/bin/env bash

set -euo pipefail

: > "${FLUTTER_CALLED:?}"
echo "update_versions.sh must not invoke Flutter" >&2
exit 70
FAKE_FLUTTER
chmod +x "$FAKE_BIN/flutter"

die() {
  local message="$1"
  local details_file="${2:-}"

  echo "  $message" >&2
  if [[ -n $details_file && -f $details_file ]]; then
    sed -n '1,180p' "$details_file" >&2
  fi
  exit 1
}

assert_file_contains() {
  local file="$1"
  local expected="$2"

  grep -Fq -- "$expected" "$file" ||
    die "expected $file to contain: $expected"
}

assert_files_equal() {
  local expected="$1"
  local actual="$2"
  local diff_file="$3"

  if ! diff -u "$expected" "$actual" > "$diff_file"; then
    die "files differ: $expected and $actual" "$diff_file"
  fi
}

assert_directories_equal() {
  local expected="$1"
  local actual="$2"
  local diff_file="$3"

  if ! diff -ru "$expected" "$actual" > "$diff_file"; then
    die "directories differ: $expected and $actual" "$diff_file"
  fi
}

create_fixture() {
  local fixture_name="$1"
  local fixture_root="$TEST_TMP/$fixture_name"
  local repo="$fixture_root/repo"

  mkdir -p \
    "$repo/bash" \
    "$repo/packages/ispect/example" \
    "$repo/packages/ispectify" \
    "$repo/web_logs_viewer"
  cp "$REPO_ROOT/bash/update_versions.sh" "$repo/bash/update_versions.sh"
  chmod +x "$repo/bash/update_versions.sh"

  printf 'VERSION=1.2.3-dev01\n' > "$repo/version.config"
  printf 'pre-existing version temp\n' > "$repo/version.config.tmp"
  printf 'README must remain byte-for-byte unchanged: ispect: ^0.0.1\n' \
    > "$repo/README.md"

  cat > "$repo/packages/ispect/pubspec.yaml" <<'EOF'
name: ispect
version: 0.0.1
dependencies:
  ispectify: ^0.0.1
dependency_overrides:
  ispectify:
    path: ../ispectify
EOF
  printf 'pre-existing pubspec temp\n' \
    > "$repo/packages/ispect/pubspec.yaml.tmp"

  cat > "$repo/packages/ispect/example/pubspec.yaml" <<'EOF'
name: ispect_example
dependencies:
  ispect: ^0.0.1
  ispectify: ^0.0.1
dependency_overrides:
  ispect:
    path: ..
  ispectify:
    path: ../../ispectify
EOF

  cat > "$repo/packages/ispectify/pubspec.yaml" <<'EOF'
name: ispectify
version: 0.0.1
environment:
  sdk: ^3.6.0
EOF

  cat > "$repo/web_logs_viewer/pubspec.yaml" <<'EOF'
name: web_logs_viewer
dependency_overrides:
  ispect:
    path: ../packages/ispect
  ispectify:
    path: ../packages/ispectify
dependencies:
  flutter:
    sdk: flutter
  ispect: ^0.0.1
  ispectify: ^0.0.1
  collection: ^1.19.1
EOF

  cat > "$repo/web_logs_viewer/pubspec.lock" <<'EOF'
# Generated by pub
packages:
  collection:
    dependency: "direct main"
    description:
      name: collection
      sha256: preserved-hosted-checksum
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  fixture_helper:
    dependency: transitive
    description:
      path: "../fixture_helper"
      relative: true
    source: path
    version: "9.9.9"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  ispect:
    dependency: "direct main"
    description:
      path: "../packages/ispect"
      relative: true
    source: path
    version: "0.0.1"
  ispectify:
    dependency: "direct main"
    description:
      path: "../packages/ispectify"
      relative: true
    source: path
    version: "0.0.1"
sdks:
  dart: ">=3.6.0 <4.0.0"
EOF

  echo "$repo"
}

run_updater() {
  local repo="$1"
  local output_file="$2"
  shift 2

  (
    cd "$repo"
    PATH="$FAKE_BIN:$PATH" \
      FLUTTER_CALLED="$TEST_TMP/flutter-called" \
      ./bash/update_versions.sh "$@"
  ) > "$output_file" 2>&1
}

test_bump_updates_only_owned_version_artifacts() {
  local repo
  local fixture_root="$TEST_TMP/bump"
  local output_file="$fixture_root/update.log"
  local expected_lock="$fixture_root/expected.lock"
  local expected_readme="$fixture_root/expected.README.md"

  repo="$(create_fixture bump)"
  cp "$repo/README.md" "$expected_readme"

  cat > "$expected_lock" <<'EOF'
# Generated by pub
packages:
  collection:
    dependency: "direct main"
    description:
      name: collection
      sha256: preserved-hosted-checksum
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  fixture_helper:
    dependency: transitive
    description:
      path: "../fixture_helper"
      relative: true
    source: path
    version: "9.9.9"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  ispect:
    dependency: "direct main"
    description:
      path: "../packages/ispect"
      relative: true
    source: path
    version: "1.2.3-dev02"
  ispectify:
    dependency: "direct main"
    description:
      path: "../packages/ispectify"
      relative: true
    source: path
    version: "1.2.3-dev02"
sdks:
  dart: ">=3.6.0 <4.0.0"
EOF

  if ! run_updater "$repo" "$output_file" --bump patch; then
    die "version update failed" "$output_file"
  fi

  assert_file_contains "$repo/version.config" "VERSION=1.2.3-dev02"
  assert_file_contains "$repo/packages/ispect/pubspec.yaml" \
    "version: 1.2.3-dev02"
  assert_file_contains "$repo/packages/ispect/pubspec.yaml" \
    "  ispectify: ^1.2.3-dev02"
  assert_file_contains "$repo/packages/ispect/example/pubspec.yaml" \
    "  ispect: ^1.2.3-dev02"
  assert_file_contains "$repo/web_logs_viewer/pubspec.yaml" \
    "  ispectify: ^1.2.3-dev02"
  assert_files_equal \
    "$expected_lock" \
    "$repo/web_logs_viewer/pubspec.lock" \
    "$fixture_root/lock.diff"
  assert_files_equal \
    "$expected_readme" \
    "$repo/README.md" \
    "$fixture_root/readme.diff"
  assert_file_contains "$repo/version.config.tmp" \
    "pre-existing version temp"
  assert_file_contains "$repo/packages/ispect/pubspec.yaml.tmp" \
    "pre-existing pubspec temp"

  if [[ -e $TEST_TMP/flutter-called ]]; then
    die "version update invoked Flutter"
  fi
}

test_dry_run_previews_target_without_writing() {
  local repo
  local fixture_root="$TEST_TMP/dry-run"
  local before="$fixture_root/before"
  local output_file="$fixture_root/update.log"

  repo="$(create_fixture dry-run)"
  cp -R "$repo" "$before"

  if ! run_updater "$repo" "$output_file" --dry-run --bump patch; then
    die "dry-run failed" "$output_file"
  fi

  assert_file_contains "$output_file" \
    "[INFO] Target version: 1.2.3-dev02 (dry-run=1)"
  assert_file_contains "$output_file" \
    "[CHG] web_logs_viewer/pubspec.lock path package versions -> 1.2.3-dev02"
  assert_directories_equal \
    "$before" \
    "$repo" \
    "$fixture_root/dry-run.diff"

  if [[ -e $TEST_TMP/flutter-called ]]; then
    die "dry-run invoked Flutter"
  fi
}

test_malformed_internal_path_stanza_fails_before_writing() {
  local repo
  local fixture_root="$TEST_TMP/malformed-lock"
  local before="$fixture_root/before"
  local output_file="$fixture_root/update.log"

  repo="$(create_fixture malformed-lock)"
  cat > "$repo/web_logs_viewer/pubspec.lock" <<'EOF'
packages:
  ispect:
    dependency: "direct main"
    description:
      path: "../packages/ispect"
      relative: true
    source: path
EOF
  cp -R "$repo" "$before"

  if run_updater "$repo" "$output_file" --bump patch; then
    die "malformed internal path stanza unexpectedly succeeded" "$output_file"
  fi

  assert_file_contains "$output_file" \
    "[ERR] Invalid path package stanza in web_logs_viewer/pubspec.lock: ispect"
  assert_directories_equal \
    "$before" \
    "$repo" \
    "$fixture_root/malformed.diff"
}

test_lock_is_ignored_without_local_web_path_dependencies() {
  local repo
  local fixture_root="$TEST_TMP/no-local-web-paths"
  local output_file="$fixture_root/update.log"
  local expected_lock="$fixture_root/expected.lock"

  repo="$(create_fixture no-local-web-paths)"
  cat > "$repo/web_logs_viewer/pubspec.yaml" <<'EOF'
name: web_logs_viewer
dependencies:
  flutter:
    sdk: flutter
  ispect: ^0.0.1
  ispectify: ^0.0.1
EOF
  printf 'fixture-lock: preserved\n' > "$repo/web_logs_viewer/pubspec.lock"
  cp "$repo/web_logs_viewer/pubspec.lock" "$expected_lock"

  if ! run_updater "$repo" "$output_file"; then
    die "update failed without local web path dependencies" "$output_file"
  fi

  assert_files_equal \
    "$expected_lock" \
    "$repo/web_logs_viewer/pubspec.lock" \
    "$fixture_root/lock.diff"

  if [[ -e $TEST_TMP/flutter-called ]]; then
    die "version update invoked Flutter without local web path dependencies"
  fi
}

run_test() {
  local name="$1"
  local test_function="$2"
  local status

  echo "[TEST] $name"
  set +e
  (
    set -e
    "$test_function"
  )
  status=$?
  set -e

  if [[ $status -eq 0 ]]; then
    echo "[PASS] $name"
  else
    echo "[FAIL] $name" >&2
    FAILURES=$((FAILURES + 1))
  fi
}

run_test \
  "bump updates only owned version artifacts" \
  test_bump_updates_only_owned_version_artifacts
run_test \
  "dry-run previews the target without writing" \
  test_dry_run_previews_target_without_writing
run_test \
  "malformed path stanza fails before any write" \
  test_malformed_internal_path_stanza_fails_before_writing
run_test \
  "lock is ignored without local web path dependencies" \
  test_lock_is_ignored_without_local_web_path_dependencies

if [[ $FAILURES -ne 0 ]]; then
  echo "[FAIL] $FAILURES update_versions test(s) failed" >&2
  exit 1
fi

echo "[PASS] update_versions tests"
