#!/usr/bin/env bash
# build_llms.sh — generate the repo-root llms.txt from repository metadata.
#
# Every entry is derived from pubspecs, example dirs, docs, and version.config, so the index
# stays current with no hand-edits. The full derivation map lives in bash/README.md.
#
# Usage:
#   ./bash/build_llms.sh            generate llms.txt
#   ./bash/build_llms.sh --check    verify llms.txt is up to date (CI); exit 1 on drift
#   ./bash/build_llms.sh --dry-run  print generated content without writing
#
# Exit codes:
#   0  success (or --check with no drift)
#   1  drift detected in --check mode
#   2  usage / configuration error

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
VERSION_CONFIG="$ROOT_DIR/version.config"
OUT_FILE="$ROOT_DIR/llms.txt"
ROOT_PUBSPEC="$ROOT_DIR/packages/ispect/pubspec.yaml"

# The project's brand name — a fixed proper noun, not derived data.
PROJECT_TITLE="ISpect"

RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
BLUE=$'\033[0;34m'
NC=$'\033[0m'

# Reads the first "key: value" line from a pubspec, stripping quotes.
pubspec_field() {
  grep -m1 "^$2:" "$1" 2>/dev/null | sed "s/^$2:[[:space:]]*//;s/^[\"']//;s/[\"']$//" || true
}

# Title-cases an interceptor filename: flutter_secure_storage_interceptor.dart → Flutter Secure Storage
pretty_name() {
  local base="${1##*/}"
  base="${base%.dart}"
  base="${base%_interceptor}"
  echo "$base" | awk -F_ '{for (i = 1; i <= NF; i++) $i = toupper(substr($i, 1, 1)) substr($i, 2); print}' OFS=' '
}

# Path relative to the repo root.
rel() { echo "${1#"$ROOT_DIR"/}"; }

# First example entrypoint for a package, repo-relative, or empty if none.
example_entry() {
  local dir="$1"
  for candidate in "$dir/example/lib/main.dart" "$dir/example/main.dart"; do
    [ -f "$candidate" ] && { rel "$candidate"; return; }
  done
  local first
  first="$(find "$dir/example/lib" "$dir/example" -maxdepth 1 -name '*.dart' ! -name '*.g.dart' 2>/dev/null | sort | head -n1)"
  [ -n "$first" ] && rel "$first"
}

generate() {
  local version repo summary
  version="$(head -n1 "$VERSION_CONFIG" | sed 's/^VERSION=//')"
  repo="$(pubspec_field "$ROOT_PUBSPEC" repository)"
  summary="$(pubspec_field "$ROOT_PUBSPEC" description)"

  echo "<!-- Generated by bash/build_llms.sh — do not edit by hand. Rerun the script after changing packages, interceptors, or docs. -->"
  echo
  echo "# ${PROJECT_TITLE}"
  echo
  echo "> ${summary}"
  echo
  echo "ISpect is a Flutter/Dart monorepo of focused diagnostics packages. This index points AI"
  echo "agents and tooling at the canonical, always-current sources so they can read what they"
  echo "need on demand instead of working from memorized API. Treat each package's exported"
  echo "\`lib/<package>.dart\` and \`README.md\` as the authoritative API surface."
  echo
  echo "- Repository: ${repo}"
  echo "- Version: ${version}"
  echo

  echo "## Integration prompt"
  echo
  if [ -f "$ROOT_DIR/docs/prompt.md" ]; then
    echo "- [docs/prompt.md](docs/prompt.md): paste-ready prompt for an AI agent to integrate ISpect into a Flutter app."
  fi
  echo

  echo "## Packages"
  echo
  local dir name desc
  while IFS= read -r dir; do
    [ -f "$dir/pubspec.yaml" ] || continue
    name="$(pubspec_field "$dir/pubspec.yaml" name)"
    desc="$(pubspec_field "$dir/pubspec.yaml" description)"
    [ -n "$name" ] || continue
    echo "- [${name}]($(rel "$dir")/README.md): ${desc}"
  done < <(find "$ROOT_DIR/packages" -mindepth 1 -maxdepth 1 -type d | sort)
  echo

  echo "## Setup examples"
  echo
  local entry
  while IFS= read -r dir; do
    name="$(pubspec_field "$dir/pubspec.yaml" name)"
    [ -n "$name" ] || continue
    entry="$(example_entry "$dir")"
    [ -n "$entry" ] && echo "- [${entry}](${entry}): example wiring for \`${name}\`."
  done < <(find "$ROOT_DIR/packages" -mindepth 1 -maxdepth 1 -type d | sort)
  echo

  local db_dir="$ROOT_DIR/packages/ispectify_db/example/lib/interceptors"
  if [ -d "$db_dir" ]; then
    echo "## Database interceptors (reference implementations to copy)"
    echo
    local f
    while IFS= read -r f; do
      echo "- [$(pretty_name "$f")]($(rel "$f"))"
    done < <(find "$db_dir" -maxdepth 1 -name '*.dart' | sort)
    echo
  fi

  local ws_dir="$ROOT_DIR/packages/ispectify_ws/example/lib/interceptors"
  if [ -d "$ws_dir" ]; then
    echo "## WebSocket adapters (reference implementations to copy)"
    echo
    while IFS= read -r f; do
      echo "- [$(pretty_name "$f")]($(rel "$f"))"
    done < <(find "$ws_dir" -maxdepth 1 -name '*.dart' | sort)
    echo
  fi

  echo "## Docs"
  echo
  local doc doc_title
  while IFS= read -r doc; do
    [ "$(basename "$doc")" = "prompt.md" ] && continue
    doc_title="$(grep -m1 '^# ' "$doc" 2>/dev/null | sed 's/^#[[:space:]]*//')"
    [ -n "$doc_title" ] || doc_title="$(basename "${doc%.md}")"
    echo "- [${doc_title}]($(rel "$doc"))"
  done < <(find "$ROOT_DIR/docs" -maxdepth 1 -name '*.md' | sort)
}

main() {
  local mode="write"
  case "${1:-}" in
    --check) mode="check" ;;
    --dry-run) mode="dry-run" ;;
    "") mode="write" ;;
    *) echo "${RED}Unknown option: $1${NC}" >&2; echo "Usage: $0 [--check|--dry-run]" >&2; exit 2 ;;
  esac

  [ -f "$VERSION_CONFIG" ] || { echo "${RED}Missing version.config${NC}" >&2; exit 2; }

  local content
  content="$(generate)"

  case "$mode" in
    dry-run)
      echo "$content"
      ;;
    check)
      if [ -f "$OUT_FILE" ] && diff -q <(printf '%s\n' "$content") "$OUT_FILE" >/dev/null; then
        echo "${GREEN}✓ llms.txt is up to date${NC}"
      else
        echo "${RED}✗ llms.txt is out of date — run ./bash/build_llms.sh${NC}" >&2
        exit 1
      fi
      ;;
    write)
      printf '%s\n' "$content" > "$OUT_FILE"
      echo "${GREEN}✓ Generated${NC} ${BLUE}$(rel "$OUT_FILE")${NC}"
      ;;
  esac
}

main "$@"
