name: Version Validation

on:
  pull_request:
    branches:
      - main
      - master
      - develop
    paths:
      - 'packages/*/pubspec.yaml'
      - 'version.config'
      - 'CHANGELOG.md'

jobs:
  validate-versions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check Version Sync
        id: check_versions
        run: |
          chmod +x bash/check_version_sync.sh
          if ! ./bash/check_version_sync.sh; then
            echo "Version check failed. Please run './bash/update_versions.sh' to sync all package versions."
            exit 1
          fi
          
      - name: Check Dependencies Consistency
        id: check_dependencies
        run: |
          chmod +x bash/check_dependencies.sh
          if ! ./bash/check_dependencies.sh; then
            echo "Dependency version check failed. Please run './bash/update_versions.sh' to sync all package dependencies."
            exit 1
          fi
      
      - name: Validate CHANGELOG
        id: validate_changelog
        run: |
          # Check if version.config exists
          if [ ! -f version.config ]; then
            echo "Error: version.config file not found. Please create it with VERSION=x.y.z format."
            exit 1
          fi
          
          # Source the version config
          if ! source version.config; then
            echo "Error: Failed to source version.config. Please check the file format."
            exit 1
          fi
          
          # Validate that VERSION variable is set
          if [ -z "$VERSION" ]; then
            echo "Error: VERSION variable is not set in version.config. Expected format: VERSION=x.y.z"
            exit 1
          fi
          
          # Check for proper CHANGELOG format
          if ! grep -qF "# Changelog" CHANGELOG.md; then
            echo "CHANGELOG.md does not start with '# Changelog'. Please fix the format."
            exit 1
          fi
          
          # Check if current version exists in CHANGELOG
          if ! grep -qF "## $VERSION" CHANGELOG.md; then
            echo "Current version $VERSION is not documented in CHANGELOG.md. Please update the changelog."
            exit 1
          fi
          
          echo "CHANGELOG validation passed!"
