name: ispectify_db
description: Database logging utilities for ISpect toolkit (passive DB observability)
version: 4.4.3-dev02
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependency_overrides:
  ispectify:
    path: ../ispectify

dependencies:
  ispectify: ^4.4.3-dev02

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
