name: ispectify_db
description: Database query logging integration for ISpect toolkit
version: 4.3.6
homepage: https://github.com/yelmuratoff/ispect.git
issue_tracker: https://github.com/yelmuratoff/ispect/issues

environment:
  sdk: ">=3.6.0 <4.0.0"

dependency_overrides:
  ispectify:
    path: ../ispectify

dependencies:
  ansicolor: ^2.0.3
  ispectify: ^4.3.6

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
